// This file is autogenerated when running rake app:run

import Appsignal from "@appsignal/javascript";

const appsignal = new Appsignal({
  key: "FRONTEND-PUSH-API-KEY",
  revision: "111111"
});

export default appsignal;
